-- Reminders app schema (PostgreSQL)
-- This file is intended to be applied statement-by-statement via psql:
--   psql ... -c "<ONE SQL STATEMENT>"
--
-- Notes:
-- - Keep this file idempotent (IF NOT EXISTS / DROP ... IF EXISTS as appropriate).
-- - The running DB already contains these objects; this file is the repo source of truth.

CREATE TABLE IF NOT EXISTS public.reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    due_date TIMESTAMPTZ NOT NULL,
    notification_at TIMESTAMPTZ,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_reminders_set_updated_at ON public.reminders;

CREATE TRIGGER trg_reminders_set_updated_at
BEFORE UPDATE ON public.reminders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_reminders_due_date
ON public.reminders USING btree (due_date);

CREATE INDEX IF NOT EXISTS idx_reminders_completed_due_date
ON public.reminders USING btree (completed, due_date);

CREATE INDEX IF NOT EXISTS idx_reminders_notification_at
ON public.reminders USING btree (notification_at)
WHERE (notification_at IS NOT NULL AND completed = false);
